# -*- coding: utf-8 -*-
"""gspread_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ua9Azaot-Q_vxEVD5xMYH7lnwbShBsgg
"""

import streamlit as st
import gspread
from oauth2client.service_account import ServiceAccountCredentials

def gspread_test():
  # Google Sheets APIの認証情報を設定
  scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
  creds = ServiceAccountCredentials.from_json_keyfile_name("path/to/your/credentials.json", scope)
  client = gspread.authorize(creds)

  # スプレッドシートを開く
  spreadsheet_url = "https://docs.google.com/spreadsheets/d/12hjoNV-0tZaxcFZ3NR5WE8UfbE6FKbWorSKkIRRdj3I/edit?gid=0#gid=0"
  sheet = client.open_by_url(spreadsheet_url).worksheet("シート1")
  # A1セルに「gspreadテスト」と書き込む
  sheet.update_cell(1, 1, "gspreadテスト")

def main():
  # Streamlitアプリケーション
  st.title("Googleスプレッドシート転記アプリ")

  if st.button("転記"):
    gspread_test()
    st.success("A1セルに「gspreadテスト」と書き込みました。")


if __name__ == "__main__":
    main()  # mainを呼び出す

